prompts:
  EarlyAlpha:
    prompt: |
    coins:
      - "Bitcoin (BTC)"
  MacroNews:
    prompt: |
    coins:
      - "Chainlink (LINK)"
  PortfolioInsights:
    prompt: |
    coins:
      - "Chainlink (LINK)"
  AlphaTrenches:
    prompt: |
    coins:
      - "Chainlink (LINK)"