import localFont from "next/font/local";
import "./globals.css";

const rethinkSans = localFont({
  src: "./fonts/RethinkSans-VariableFont_wght.ttf",
  variable: "--font-rethink-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${rethinkSans.className} bg-black antialiased`}
      >
       <div className="mx-auto max-w-[1400px]">
          {children}
        </div>
      </body>
    </html>
  );
}
