version: '3.1'
services:
  app:
    build:
      context: ./finowl-backend  # Adjusted path to backend
    container_name: finowl-app
    depends_on:
      - db
      - frontend  # Ensure frontend is still a dependency
    environment:
      - FINOWL_DB_HOST=db
      - FINOWL_DB_PORT=5432
      - FINOWL_DB_USER=finowl_user
      - FINOWL_DB_PASSWORD=finowl_pass
      - FINOWL_DB_NAME=finowl_db
    volumes:
      - ./finowl-backend/config.yaml:/app/config.yaml
      - ./finowl-backend/influencers.yaml:/app/influencers.yaml
      - ./finowl-backend/logs:/app/logs
      - ./finowl-backend/.env:/app/.env
      - ./finowl-backend/prompt.txt:/app/prompt.txt
    ports:
      - "8080:8080"
    networks:
      - finowl-network

  db:
    image: postgres:15-alpine
    container_name: finowl-db
    environment:
      - POSTGRES_USER=finowl_user
      - POSTGRES_PASSWORD=finowl_pass
      - POSTGRES_DB=finowl_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - finowl-network

  frontend:  # New frontend service
    build:
      context: ./frontend  # Adjusted path to frontend
    container_name: finowl-frontend
    ports:
      - "3000:3000"  # Expose frontend port
    networks:
      - finowl-network

volumes:
  postgres_data:

networks:
  finowl-network:
    driver: bridge