name: Go Tests

on:
  push:
    branches:
      - '**'  # Trigger on pushes to any branch
  pull_request:
    branches:
      - '**'  # Trigger on pull requests to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Change Directory
        run: cd finowl-backend  # Change to the Go project directory

      - name: Run Tests and Check Coverage
        run: |
          cd finowl-backend  # Ensure we are in the correct directory
          go test -cover ./...  # Run tests and check coverage